---
name: Build Main

"on":
  push:
    branches: [main]

env:
  # renovate: datasource=npm depName=@semantic-release/changelog
  SEMANTIC_RELEASE_CHANGELOG_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/git
  SEMANTIC_RELEASE_GIT_VERSION: 10.0.1

  # renovate: datasource=npm depName=conventional-changelog-conventionalcommits
  CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION: 6.1.0

  # renovate: datasource=npm depName=gradle-semantic-release-plugin
  GRADLE_SEMANTIC_RELEASE_PLUGIN_VERSION: 1.7.4

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    with:
      continue-on-error: true

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true

  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-release

    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          distribution: temurin
          # renovate: datasource=java-version depName=java
          java-version: 17.0.8+101

      - name: Setup Gradle
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0

      - name: Release
        id: release
        # yamllint disable-line rule:line-length
        uses: cycjimmy/semantic-release-action@61680d0e9b02ff86f5648ade99e01be17f0260a4 # v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          # renovate: datasource=npm depName=semantic-release
          semantic_version: 19.0.5
          extra_plugins:
            "@semantic-release/changelog@\
            ${{ env.SEMANTIC_RELEASE_CHANGELOG_VERSION }} \
            @semantic-release/git@\
            ${{ env.SEMANTIC_RELEASE_GIT_VERSION }} \
            conventional-changelog-conventionalcommits@\
            ${{ env.CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION }} \
            gradle-semantic-release-plugin@\
            ${{ env.GRADLE_SEMANTIC_RELEASE_PLUGIN_VERSION }}"
