---
name: Lint

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Lint
        # yamllint disable-line rule:line-length
        uses: super-linter/super-linter/slim@ba3315d7e5da8cee94ef552f3baf1c34f6021345 # v5.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          YAML_ERROR_ON_WARNING: true
          FILTER_REGEX_EXCLUDE: (.*gradlew.*|.*day-.+-input-.+\.txt)
