---
name: Lint

"on":
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0

      - name: Lint
        # yamllint disable-line rule:line-length
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v4.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          YAML_ERROR_ON_WARNING: true
          FILTER_REGEX_EXCLUDE: (.*gradlew.*|.*day-.+-input-.+\.txt)
