---
name: Lint

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Lint
        # yamllint disable-line rule:line-length
        uses: super-linter/super-linter/slim@a8150b40c89574adb5f68bf9502b890a236a06b3 # v5.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          YAML_ERROR_ON_WARNING: true
          FILTER_REGEX_EXCLUDE: (.*gradlew.*|.*day-.+-input-.+\.txt)
