---
name: Test

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          # renovate: datasource=java-version depName=java
          java-version: 17.0.10+7

      - name: Test
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          arguments: test jacocoTestReport

      - name: Upload test coverage to Codecov
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
