---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: temurin
          # renovate: datasource=java-version depName=java
          java-version: 17.0.6+10

      - name: Test
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2.4.0
        with:
          arguments: test jacocoTestReport

      - name: Upload test coverage to Codecov
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
