---
name: Test

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false
    secrets:
      CODECOV_TOKEN:
        description: The token used by Codecov
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          # renovate: datasource=java-version depName=java
          java-version: 17.0.10+7

      - name: Setup Gradle
        # yamllint disable-line rule:line-length
        uses: gradle/actions/setup-gradle@e24011a3b5db78bd5ab798036042d9312002f252 # v3.2.0

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: Upload test coverage to Codecov
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@7afa10ed9b269c561c2336fd862446844e0cbf71 # v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
