---
name: Test

"on":
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: Allow a workflow run to pass when this workflow fails
        required: false
        default: false
    secrets:
      CODECOV_TOKEN:
        description: The token used by Codecov
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          # renovate: datasource=java-version depName=java
          java-version: 21.0.4+7.0.LTS

      - name: Setup Gradle
        # yamllint disable-line rule:line-length
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: Upload test coverage to Codecov
        # yamllint disable-line rule:line-length
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
