---
name: Update Dependencies

"on":
  schedule:
    - cron: 0/15 * * * *

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Get token
        id: get-token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # tag=v2.1.0
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write,
            workflows:write

      - name: Update dependencies
        # yamllint disable-line rule:line-length
        uses: renovatebot/github-action@23a02fe7be9e93f857a953cc8162e57d2c8401ef # v39.0.1
        with:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 36.64.1
          configurationFile: renovate.json5
          token: x-access-token:${{ steps.get-token.outputs.token }}
