---
name: Update Dependencies

"on":
  schedule:
    - cron: 0/15 * * * *

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get token
        id: get-token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974 # v4.0.0
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          revoke_token: true
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write,
            workflows:write

      - name: Update dependencies
        # yamllint disable-line rule:line-length
        uses: renovatebot/github-action@80eaf969abf68ad62aa94d9ab392421b31621634 # v40.3.4
        with:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 37.440.7
          configurationFile: renovate.json5
          token: x-access-token:${{ steps.get-token.outputs.token }}
